services:
  app:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rishabh
      POSTGRES_DB: social_db
volumes:
  db_data: