"""v2_change all places

Revision ID: 0712e9c280db
Revises: 5645f76eddc5
Create Date: 2025-01-16 18:00:24.027342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0712e9c280db'
down_revision: Union[str, None] = '5645f76eddc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('otp_user_id_fkey', 'otp', type_='foreignkey')
    op.create_foreign_key(None, 'otp', 'users', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'otp', type_='foreignkey')
    op.create_foreign_key('otp_user_id_fkey', 'otp', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
