"""v4 add like column in post

Revision ID: 32ab8277755d
Revises: 0712e9c280db
Create Date: 2025-01-16 22:38:49.117977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ab8277755d'
down_revision: Union[str, None] = '0712e9c280db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'like_count')
    # ### end Alembic commands ###
