"""change all places

Revision ID: 5645f76eddc5
Revises: 405caac7613c
Create Date: 2025-01-16 17:47:00.652392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5645f76eddc5'
down_revision: Union[str, None] = '405caac7613c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_like_post_id_fkey', 'comment_like', type_='foreignkey')
    op.drop_constraint('comment_like_comment_id_fkey', 'comment_like', type_='foreignkey')
    op.drop_constraint('comment_like_user_id_fkey', 'comment_like', type_='foreignkey')
    op.create_foreign_key(None, 'comment_like', 'comments', ['comment_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'comment_like', 'posts', ['post_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'comment_like', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='cascade')
    op.drop_constraint('like_user_id_fkey', 'like', type_='foreignkey')
    op.drop_constraint('like_post_id_fkey', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'like', 'posts', ['post_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_post_id_fkey', 'like', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('like_user_id_fkey', 'like', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'comment_like', type_='foreignkey')
    op.drop_constraint(None, 'comment_like', type_='foreignkey')
    op.drop_constraint(None, 'comment_like', type_='foreignkey')
    op.create_foreign_key('comment_like_user_id_fkey', 'comment_like', 'users', ['user_id'], ['id'])
    op.create_foreign_key('comment_like_comment_id_fkey', 'comment_like', 'comments', ['comment_id'], ['id'])
    op.create_foreign_key('comment_like_post_id_fkey', 'comment_like', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
